# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config  -id {Labtools 27-3164}  -string {{INFO: [Labtools 27-3164] End of startup status: HIGH}}  -suppress 
set_msg_config  -id {Labtoolstcl 44-129}  -string {{WARNING: [Labtoolstcl 44-129] No matching hw_ila_data was found.}}  -suppress 
set_msg_config  -id {Labtools 27-2285}  -string {{INFO: [Labtools 27-2285] Connecting to hw_server url TCP:localhost:3121}}  -suppress 
set_msg_config  -id {Labtools 27-2222}  -string {{INFO: [Labtools 27-2222] Launching hw_server...}}  -suppress 
set_msg_config  -id {Labtools 27-2221}  -string {{INFO: [Labtools 27-2221] Launch Output:

****** Xilinx hw_server v2018.3
  **** Build date : Dec  7 2018-00:40:27
    ** Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.}}  -suppress 
set_msg_config  -id {Labtoolstcl 44-513}  -string {{ERROR: [Labtoolstcl 44-513] HW Target shutdown. Closing target: localhost:3121/xilinx_tcf/Digilent/C305B9FFABCD}}  -suppress 
set_msg_config  -string {{Scanning sources...}}  -suppress 
set_msg_config  -id {IP_Flow 19-234}  -string {{INFO: [IP_Flow 19-234] Refreshing IP repositories}}  -suppress 
set_msg_config  -id {IP_Flow 19-1704}  -string {{INFO: [IP_Flow 19-1704] No user IP repositories specified}}  -suppress 
set_msg_config  -id {IP_Flow 19-2313}  -string {{INFO: [IP_Flow 19-2313] Loaded Vivado IP repository 'E:/Xilinx/Vivado/2018.3/data/ip'.}}  -suppress 
set_msg_config  -id {Vivado 12-1017}  -string {{WARNING: [Vivado 12-1017] Problems encountered:
1. PID not specified}}  -suppress 
set_msg_config  -id {Labtools 27-1434}  -string {{INFO: [Labtools 27-1434] Device xc7a35t (JTAG device index = 0) is programmed with a design that has no supported debug core(s) in it.}}  -suppress 
set_msg_config  -id {Labtoolstcl 44-466}  -string {{INFO: [Labtoolstcl 44-466] Opening hw_target localhost:3121/xilinx_tcf/Digilent/C305B9FFABCD}}  -suppress 
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/vivadocode/uart_loopback_top/uart_loopback_top.cache/wt [current_project]
set_property parent.project_path E:/vivadocode/uart_loopback_top/uart_loopback_top.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/vivadocode/uart_loopback_top/uart_loopback_top.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/vivadocode/uart_loopback_top/uart_loopback_top.srcs/sources_1/new/seven_tube_drive.v
  E:/vivadocode/uart_loopback_top/uart_loopback_top.srcs/sources_1/new/uart_ctrl.v
  E:/vivadocode/uart_loopback_top/uart_loopback_top.srcs/sources_1/new/uart_recv.v
  E:/vivadocode/uart_loopback_top/uart_loopback_top.srcs/sources_1/new/uart_send.v
  E:/vivadocode/uart_loopback_top/uart_loopback_top.srcs/sources_1/new/uart_loopback_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/vivadocode/uart_loopback_top/uart_loopback_top.srcs/constrs_1/new/uart_loopback_top.xdc
set_property used_in_implementation false [get_files E:/vivadocode/uart_loopback_top/uart_loopback_top.srcs/constrs_1/new/uart_loopback_top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top uart_loopback_top -part xc7a35tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef uart_loopback_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file uart_loopback_top_utilization_synth.rpt -pb uart_loopback_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
